package com.C1709L.project.matrimony.model;
// Generated Aug 19, 2017 5:24:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FriendsRequest generated by hbm2java
 */
@Entity
@Table(name = "friends_request", catalog = "matrimony")
public class FriendsRequest implements java.io.Serializable {

	private Long id;
	private Long idUserRequest;
	private Long idUserReceive;
	private Boolean status;

	public FriendsRequest() {
	}

	public FriendsRequest(Long idUserRequest, Long idUserReceive, Boolean status) {
		this.idUserRequest = idUserRequest;
		this.idUserReceive = idUserReceive;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "id_user_request")
	public Long getIdUserRequest() {
		return this.idUserRequest;
	}

	public void setIdUserRequest(Long idUserRequest) {
		this.idUserRequest = idUserRequest;
	}

	@Column(name = "id_user_receive")
	public Long getIdUserReceive() {
		return this.idUserReceive;
	}

	public void setIdUserReceive(Long idUserReceive) {
		this.idUserReceive = idUserReceive;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
