package com.C1709L.project.matrimony.model;
// Generated Aug 19, 2017 5:24:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Friends generated by hbm2java
 */
@Entity
@Table(name = "friends", catalog = "matrimony")
public class Friends implements java.io.Serializable {

	private Long id;
	private Long idUserRequest;
	private Long idUserAccept;

	public Friends() {
	}

	public Friends(Long idUserRequest, Long idUserAccept) {
		this.idUserRequest = idUserRequest;
		this.idUserAccept = idUserAccept;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "id_user_request")
	public Long getIdUserRequest() {
		return this.idUserRequest;
	}

	public void setIdUserRequest(Long idUserRequest) {
		this.idUserRequest = idUserRequest;
	}

	@Column(name = "id_user_accept")
	public Long getIdUserAccept() {
		return this.idUserAccept;
	}

	public void setIdUserAccept(Long idUserAccept) {
		this.idUserAccept = idUserAccept;
	}

}
